### PR TITLE
ADD event details

### PR DESCRIPTION
**Pull request by AdnanMuhib**
Added the event details in my own words.

### CODE REVIEW

**Comment by ahmadawais** [comment]
Thanks, Adnan. It looks pretty good but I think it should have been in a separate file. Anywho, welcome aboard. And keep up the good work, I saw your profile, it looks like you are headed in the right direction here. I hope you make your four PR's this month. Add git resources to this repo. One resource per PR.

**Comment by AdnanMuhib** [comment]
hactoberfest challenge completed
Thanks, @ahmadawais for this. Finally four PR's and completed the challenge.

**Comment by ahmadawais** [comment]
I'm so glad for you, @AdnanMuhib! Keep it up.

Also, I think you were the first one to complete the challenge. Feel free to ask for a WP-Pakistan T-Shirt from me if and when you're in Bahria Lahore.

**Comment by AdnanMuhib** [comment]
Thank you so much for your co-operation @ahmadawais 😍, it wouldn't have been possible without your guidance. Sure I'll be glad to take the **WP-Pakistan** shirt. It would be nice of you if you handover to **Saqib Ameen** if he meets you before me, I'll take from him. 
And of course waiting for the #DigitalOcean Shirt too. 😃

**Comment by ahmadawais** [comment]
Reach out to me some time and we should def talk. Keep up the good work!

**Comment by AdnanMuhib** [comment]
of course I'll.

**Pull request merged**
